### ISSUE TITLE
Simple integration :: transactionReference is null

### ISSUE THREAD

**Issue by BOAndrew** [hipay/hipay-fullservice-sdk-android#38]
In onActivityResult after a successful payment with HiPay SDK simple integration, I get the transaction from bundle with the following line of code:
`Transaction transaction = Transaction.fromBundle(transactionBundle);`
At this point it looks like some transaction details are missing. For example:
`transaction.getTransactionReference() `returns `null`

All the transaction details are available in `PaymentFormActivity`, in method 
`private FormResult manageTransactionState(Transaction transaction)` at line `364`:
`intent.putExtra(Transaction.TAG, transaction.toBundle()); //transactionReference is non-null here`

I believe the bug is at line `34` in `TransactionRelatedItemSerialization.java`, 
in method `public Bundle getSerializedBundle()`.
Instead of using the `TransactionRelatedItem` instance which was passed via constructor argument , a new object is instantiated:
`TransactionRelatedItem object = new TransactionRelatedItem();`

**Comment by nfillion21** [comment]
Good catch, thanks.
I will release a new version in a few hours.

**Comment by nfillion21** [comment]
Bug fixed in version 1.1.0
