### ISSUE TITLE
Crash when removing the first character from the card number when it's a space.

### ISSUE THREAD

**Issue by mayardb** [hipay/hipay-fullservice-sdk-android#46]
Hi HiPay team.

I crash when I remove the first character of the card number if it is the space " " from the card number.
I am using  `compile 'com.hipay.fullservice:hipayfullservice:1+'` so I have your last sdk version (1.3.1).

> 05-02 14:35:18.124 23537-23537/ D/Error: ERR: stack=java.lang.IndexOutOfBoundsException: replace (-1 ... 0) starts before 0
>                                                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
>                                                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
>                                                      at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$GenericTextWatcher.afterTextChanged(TokenizableCardPaymentFormFragment.java:645)
>                                                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8202)
>                                                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10381)
>                                                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
>                                                  	at android.text.SpannableStringBu

**Comment by jtiret** [comment]
Hi @mayardb,

Thanks for opening this issue. We will look at it and come back to you quickly.

Jonathan

**Comment by nfillion21** [comment]
Hello @mayardb!

Good catch, this bug is resolved in our last version 1.3.2

Nicolas

**Comment by mayardb** [comment]
Thanks for the quick fix!

Bastien.
