### ISSUE TITLE
Focusing the username field first

### ISSUE THREAD

**Issue by mayardb** [hipay/hipay-fullservice-sdk-android#48]
Hi HiPay team.

when i open HiPay with the easiest integration, I notice that the card number is the field focused in the new card input screen.

Can you consider focusing the user name first since it is required and empty ?

Thank you for the improvement.

**Comment by aymericfc** [comment]
Hello mayardb,

Thank you for your message and your consideration. You have a good point here but there is a reason why we don't focus on the name first.

As a matter effect this field is often completed with the name the merchant provide. However we can think on an upgrade when the merchant don't provide the name and we can focus on the first field. 

We will try do study that change and make in the the roadmap if we can.

Regards,
Aymeric.
