### ISSUE TITLE
Incorrect Credentials when using production account

### ISSUE THREAD

**Issue by BOAndrew** [hipay/hipay-fullservice-sdk-android#50]
Everything works fine when using a staging account.
However, when I use credentials for Production/Live account I receive the generic error message:
"Your request could not be completed". 

This happens when requesting the list of available payment products.
The underlying error is:
`{
  "code" : "100001",
  "message": "Incorrect Credentials : Insufficient Privilege",
  "description": ""
}`
**This problem does not occur with the SDK for iOS.** However, I noticed that iOS SDK uses `/rest/v2/`
Although all I changed in the Android project was the environment, username and password, I decided to test this further and to make sure that the problem is not from my code.
I changed the passphrase for the production account to `32JUWB3veDWWmHySNJvtvPyBnqrDFEHbaP3jr` in order to test with **the example project provided in this github repo. I get the same error.**

Let me now if you need more info about this issue.

Please treat this issue with high priority because it prevents us from releasing an app after successfully testing it for a long time using a staging account.

**Comment by nfillion21** [comment]
Hello,

Can you give me your username ? Then I can check what happens in the backlogs

**Comment by BOAndrew** [comment]
Hello,

Production API username: **94659144.secure-gateway.hipay-tpp.com**
Staging API username (working): **94658257.stage-secure-gateway.hipay-tpp.com**

**Comment by nfillion21** [comment]
Hello,

It was indeed a production URL problem, this bug is resolved in our last version 1.3.3.
Sorry for the inconvenience.
