### ISSUE TITLE
Incorrect connection string on SecureVaultClient

### ISSUE THREAD

**Issue by charles-awayup** [hipay/hipay-fullservice-sdk-android#64]
Hi,

Few days ago, you have released a new version of SDK (v.1.4.0).
Something wrongs here : 

https://github.com/hipay/hipay-fullservice-sdk-android/commit/a81cacb1b45492cbdaf0696fd6b7d5d41edadd23

As you can see, the connection string about SecureVaultClientBaseURLProduction is incorrect for Production Environment.

Can you please fix that quickly ?

Thanks a lot

**Comment by Olousouzian** [comment]
You can close this ticket, this issue is now fixed by the commit https://github.com/hipay/hipay-fullservice-sdk-android/commit/e2a2bdb2ad1b31cf3d625aed01fc84dfc86b0bdc

Thanks for the no response BTW...
