### ISSUE TITLE
Error Dialog with Transaction Completed

### ISSUE THREAD

**Issue by fed933** [hipay/hipay-fullservice-sdk-android#73]
On version 1.6.3 of your sdk integrated with fast integration in app when the user pay with a saved card (so using PaymentCardsActivity) and the transaction is in TransactionStateCompleted or TransactionStatePending it will  be merged with FormActionQuit as form result. 

This will cause the opening of a dialog with the following message res id
Title: R.string.alert_error_default_title -> An error occurred
Content: R.string.alert_error_default_body -> Your request could not be completed

**Comment by morganHipay** [comment]
Thanks for submitting this bug.
We fix it in the last version **1.6.4** : https://github.com/hipay/hipay-fullservice-sdk-android/releases/tag/1.6.4
