### ISSUE TITLE
Target SDK version 31

### ISSUE THREAD

**Issue by KevynBct** [hipay/hipay-fullservice-sdk-android#74]
Hello,

When we set the targetSDKVersion to 31, we get this error : 

`Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.`

To resolve this, we have to edit manually the Hipay's section in the manifest at each gradle sync.

**Comment by morganHipay** [comment]
Hello,
We upgraded _targetSDKVersion_ to 31 in the last version [1.7.0](https://github.com/hipay/hipay-fullservice-sdk-android/releases/tag/1.7.0)
