### ISSUE TITLE
Android API Target should be API 34 (and min API can be 21)

### ISSUE THREAD

**Issue by benju69** [hipay/hipay-fullservice-sdk-android#76]
You should target the last version of Android
Also I don't see why min sdk is now 23

And please update your doc :)

`PREREQUISITES
Build settings  

The project minSdkVersion is 14 (Ice Cream Sandwich), which means that the SDK won’t build on applications targeting a lower version of Android.`

**Comment by thibautgdt** [comment]
We have updated the minSdk to 25 and the targetSdk to 35.
We will closed this issue.

Thanks :)
