### ISSUE TITLE
Failed to resolve: com.hipay.fullservice:hipayfullservice:2.1.1

### ISSUE THREAD

**Issue by benju69** [hipay/hipay-fullservice-sdk-android#78]
Could not find com.hipay.fullservice:hipayfullservice:2.1.1.
last version is not on maven? https://mvnrepository.com/artifact/com.hipay.fullservice/hipayfullservice
can you check @stormwind85 ?

**Comment by stormwind85** [comment]
Hi @benju69 !

My apologies to not publish the latest version on Maven.

It should be published at this moment, could you check it now ?

**Comment by benju69** [comment]
looks good now
